### PR TITLE
Brp-59

### PR DESCRIPTION
**Pull request by hjvoid**
**### What?**
Optional date fields were not acting as optional due to a validation behaviour being in place.

**### Why?**
Bug fix.

**### How?**
Validation behaviour has been removed.

**### Testing?**
lint, acceptance and amended unit tests all run locally.

### CODE REVIEW

**Review by Rhodine — COMMENTED** [review]
The validation has now been removed but if you check the ‘I don’t have the letter anymore’ box or select the ‘no’ radio button the next page shows ‘We need to know the date on your letter to find your BRP…’ so the messaging might have to change there if giving the date is now optional.

**Comment by hjvoid** [comment]
I think this is dealt with in the next paragraph isn't it? _"If you think you should have received the letter by now, or you no longer have your letter, contact [UK Visas and Immigration](https://www.gov.uk/contact-ukvi/visas-and-settlement)."_

**Comment by Rhodine** [comment]
I think its good you added "If you think you should have received the letter by now, or you no longer have your letter, contact..."  I just thought that if the date is optional, it didn't really need "We need to know the date..."

**Review by Rhodine — APPROVED** [review]
looks good

**Pull request merged**
